package com.pigtrax.pigevents.controller;

import javax.servlet.http.HttpServletRequest;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.pigtrax.pigevents.service.interfaces.FeedEventDetailService;
import com.pigtrax.pigevents.service.interfaces.FeedEventService;
import com.pigtrax.usermanagement.beans.Company;
import com.pigtrax.usermanagement.beans.PigTraxUser;
import com.pigtrax.usermanagement.service.interfaces.CompanyService;

@Controller
public class FeedEventController {
	
 private static final Logger logger = Logger.getLogger(FeedEventController.class);
	 
	 @Autowired
	 FeedEventService feedEventService;
	 
	 @Autowired
	 FeedEventDetailService feedEventDetailService;
	 
	 @Autowired
	 CompanyService companyService;
	 
	 @RequestMapping(value="/feedEvent", method=RequestMethod.POST)
	   public String loadFeedEvent(HttpServletRequest request, Model model)  
	   {
		   PigTraxUser activeUser = (PigTraxUser)SecurityContextHolder.getContext().getAuthentication().getPrincipal();
		   logger.info("Compayny ID : "+activeUser.getCompanyId()+"/ Role : "+activeUser.getUserRole());
		   try{
			   if(request.getParameter("selectedCompany") != null) 
			   {
				   String companyId = request.getParameter("selectedCompany");
				   Company company = companyService.findByCompanyByAutoGeneratedId(Integer.parseInt(companyId));
				   model.addAttribute("CompanyId", Integer.parseInt(companyId));	
				   model.addAttribute("CompanyName", company.getName());
			   }
			   else
			   {
				   Company company = companyService.findByCompanyByAutoGeneratedId(activeUser.getCompanyId());
				   model.addAttribute("CompanyId", activeUser.getCompanyId());
				   model.addAttribute("CompanyName", company.getName());
			   }
			   if(request.getParameter("feedEventTicketNumber") != null) 
			   {
				   model.addAttribute("feedEventTicketNumber", request.getParameter("feedEventTicketNumber"));
			   }
		   }catch(Exception ex)
		   {
			   
		   }
		   model.addAttribute("contentUrl","feedEvent.jsp");
		   return "template";
	   }
	 
	 
	 @RequestMapping(value = "/addFeedEventDetail")
		public String addPremises(Model model)
		{
			model.addAttribute("contentUrl","addFeedEventDetail.jsp"); 
			return "addFeedEventDetail";
		}


}
