package com.pigtrax.pigevents.controller;

import javax.servlet.http.HttpServletRequest;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.pigtrax.usermanagement.beans.Company;
import com.pigtrax.usermanagement.beans.PigTraxUser;
import com.pigtrax.usermanagement.service.interfaces.CompanyService;

@Controller
public class GroupEventController {
	
 private static final Logger logger = Logger.getLogger(PregnancyEventController.class);
	 
	 @Autowired
	 CompanyService companyService;
	 
	  @RequestMapping(value="/groupEvent", method=RequestMethod.POST)
	   public String loadGroupEvent(HttpServletRequest request, Model model)  
	   {
		   PigTraxUser activeUser = (PigTraxUser)SecurityContextHolder.getContext().getAuthentication().getPrincipal();
		   logger.info("Compayny ID : "+activeUser.getCompanyId()+"/ Role : "+activeUser.getUserRole());
		   try{
			   if(request.getParameter("selectedCompany") != null) 
			   {
				   String companyId = request.getParameter("selectedCompany");
				   Company company = companyService.findByCompanyByAutoGeneratedId(Integer.parseInt(companyId));
				   model.addAttribute("CompanyId", Integer.parseInt(companyId));	
				   model.addAttribute("CompanyName", company.getName());
			   }
			   else
			   {
				   Company company = companyService.findByCompanyByAutoGeneratedId(activeUser.getCompanyId());
				   model.addAttribute("CompanyId", activeUser.getCompanyId());
				   model.addAttribute("CompanyName", company.getName());
			   }
			   if(request.getParameter("searchedGroupid") != null) 
			   {
				   model.addAttribute("searchedGroupid", request.getParameter("searchedGroupid"));
			   }
		   }catch(Exception ex)
		   {
			   
		   }
		   model.addAttribute("contentUrl","GroupEvent.jsp");
		   return "template";
	   }
	  
	  @RequestMapping(value = "/addGroupEventDetail", method=RequestMethod.POST)
		public String addPremises(HttpServletRequest request,Model model)
		{
			model.addAttribute("contentUrl","addGroupEventDetail.jsp"); 
			model.addAttribute("groupId",request.getParameter("searchedGroupid"));
			model.addAttribute("groupGeneratedId",request.getParameter("groupGeneratedIdSeq"));
			model.addAttribute("companyId",request.getParameter("companyId"));
			 
			 if(request.getParameter("groupEventId") != null) 
			   {
				 model.addAttribute("groupEventId",request.getParameter("groupEventId"));
			   }
			return "template";
		}	   

}
