package com.pigtrax.pigevents.controller;

import javax.servlet.http.HttpServletRequest;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.pigtrax.application.exception.PigTraxException;
import com.pigtrax.pigevents.beans.GroupEvent;
import com.pigtrax.pigevents.service.interfaces.FeedEventDetailService;
import com.pigtrax.pigevents.service.interfaces.FeedEventService;
import com.pigtrax.usermanagement.beans.Company;
import com.pigtrax.usermanagement.beans.PigTraxUser;
import com.pigtrax.usermanagement.service.interfaces.CompanyService;

@Controller
public class RemovalEventController 
{
	
	private static final Logger logger = Logger.getLogger(FeedEventController.class);
	 
	 @Autowired
	 CompanyService companyService;
	 
	 @RequestMapping(value="/removalEvent", method=RequestMethod.POST)
	   public String loadFeedEvent(HttpServletRequest request, Model model)  
	   {
		   PigTraxUser activeUser = (PigTraxUser)SecurityContextHolder.getContext().getAuthentication().getPrincipal();
		   logger.info("Compayny ID : "+activeUser.getCompanyId()+"/ Role : "+activeUser.getUserRole());
		   try{
			   if(request.getParameter("selectedCompany") != null) 
			   {
				   String companyId = request.getParameter("selectedCompany");
				   Company company = companyService.findByCompanyByAutoGeneratedId(Integer.parseInt(companyId));
				   model.addAttribute("CompanyId", Integer.parseInt(companyId));	
				   model.addAttribute("CompanyName", company.getName());
			   }
			   else
			   {
				   Company company = companyService.findByCompanyByAutoGeneratedId(activeUser.getCompanyId());
				   model.addAttribute("CompanyId", activeUser.getCompanyId());
				   model.addAttribute("CompanyName", company.getName());
			   }
			   if(request.getParameter("removalEventTicketNumber") != null) 
			   {
				   model.addAttribute("removalEventTicketNumber", request.getParameter("removalEventTicketNumber"));
			   }
			   if(request.getParameter("fromExcept") != null)
			   {
				   model.addAttribute("fromExcept", request.getParameter("fromExcept"));
			   }
		   }catch(Exception ex)
		   {
			   
		   }
		   model.addAttribute("contentUrl","removalEvent.jsp");
		   return "template";
	   }
	 
	 
	 @RequestMapping(value = "/addSalesEventDetails")
		public String addSalesEventDetails(Model model)
		{
			model.addAttribute("contentUrl","addSalesEventDetails.jsp"); 
			return "addRemovalEventExceptSalesDetails";
		}
	 
	 @RequestMapping(value = "/addRemovalEventExceptSalesDetails", method=RequestMethod.POST)
		public String addRemovalEventExceptSalesDetails(HttpServletRequest request, Model model)
		{
			model.addAttribute("removalIdEntered",request.getParameter("removalIdEntered"));
			model.addAttribute("removalGeneratedId",request.getParameter("removalGeneratedId"));
			model.addAttribute("removalExceptSalesId",request.getParameter("removalExceptSalesId"));
			model.addAttribute("companyId",request.getParameter("companyId"));
			model.addAttribute("removalTypeId",request.getParameter("removalTypeId1"));
			
			model.addAttribute("contentUrl","addRemovalEventExceptSalesDetails.jsp"); 
			return "template";
		}
	 
	 @RequestMapping(value = "/openSelectBox")
		public String openSelectBox(Model model)
		{
			model.addAttribute("contentUrl","openSelectBox.jsp"); 
			return "openSelectBox";
		}

}
