package com.pigtrax.master.service.interfaces;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import com.pigtrax.master.dto.Barn;
import com.pigtrax.pigevents.dto.BarnDto;

public interface BarnService {
	

	/**
	 * To get the list of Barn
	 * @return List<Barn>
	 */
	public List<Barn> getBarnList( int generatedPremisesId );
	
	
	/**
	 * To update Barn Status
	 * @return int
	 */
	
	public int updateBarnStatus(final String barnID, final Boolean barnStatus) throws SQLException;
	
	/**
	 * To Insert Barn record
	 * @return int (Success with int>0)
	 */
	
	public int insertBarnRecord(Barn barn) throws SQLException;
	
	/**
	 * To update Barn record
	 * @return Barn 
	 */
	
	public int updateBarnRecord(Barn barn) throws SQLException;
	
	/**
	 * Get List of Barns for a given Company Id
	 * @param companyId
	 * @return
	 * @throws SQLException
	 */
	List<BarnDto> getBarns(Integer companyId) throws SQLException;
	
	/**
	 * Load the Barn information based on auto generated generatedBarnId
	 * @param Barn
	 * @return
	 * @throws SQLException
	 */
	
	public Barn findByBarnByAutoGeneratedId(final int generatedBarnId) throws SQLException;
	
	/**
	 * Load the Barn information based on auto companyId
	 * @param Barn
	 * @return
	 * @throws SQLException
	 */
	public Map<Integer,String> getBarnListBasedOnCompanyId( final int generatedCompanyId ) throws SQLException;
	
}
