package com.pigtrax.master.service.interfaces;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import com.pigtrax.master.dto.Silo;

public interface SiloService {
	/**
	 * To get the list of Silo
	 * @return List<Silo>
	 */
	public List<Silo> getSiloList( int generatedBarnId );
	
	
	/**
	 * To update Silo Status
	 * @return int
	 */
	
	public int updateSiloStatus(final String siloID, final Boolean siloStatus) throws SQLException;
	
	/**
	 * To Insert Silo record
	 * @return int (Success with int>0)
	 */
	
	public int insertSiloRecord(Silo silo) throws SQLException;
	
	/**
	 * To update Silo record
	 * @return Silo 
	 */
	
	public int updateSiloRecord(Silo silo) throws SQLException;
	
	/**
	 * Load the Silo information based on auto generated generatedBarnId
	 * @param Barn
	 * @return
	 * @throws SQLException
	 */
	
	public Silo findBySiloByAutoGeneratedId(final int generatedSiloId) throws SQLException;
	
	public Map<Integer,String> getSiloListBasedOnCompanyId( int generatedCompanyId );
	
	public Map<Integer,String> getSiloListBasedOnPremiseId( Integer premiseId );
	
	Integer deleteSilo(Integer siloId);
	
}
