package com.pigtrax.master.controller;

import java.sql.SQLException;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.pigtrax.cache.RefDataCache;
import com.pigtrax.master.dto.Barn;
import com.pigtrax.master.service.interfaces.BarnService;

@Controller
public class RoomController {
	
	private static final Logger logger = Logger.getLogger(RoomController.class);

	@Autowired
	BarnService barnService;
	
	@Autowired
	RefDataCache refDataCache;
	
	@RequestMapping(value = "/room", method=RequestMethod.POST)
	public String displayRoom(Model model, @RequestParam int generatedBarnId)
	{
		System.out.println("Ankush printing---->"+generatedBarnId);
		model.addAttribute("contentUrl","room.jsp");
		model.addAttribute("generatedBarnId",generatedBarnId);
		try
		{
			Barn barn = barnService.findByBarnByAutoGeneratedId(generatedBarnId);
			if(null != barn)
			{
				model.addAttribute("barnId",barn.getBarnId());				
			}
		} 
		catch (SQLException e)
		{
			e.printStackTrace();
		}
		return "template";
	}
	
	@RequestMapping(value = "/addRoom")
	public String addRoom(Model model)
	{
		model.addAttribute("contentUrl","addRoom.jsp"); 
		return "addRoom";
	}

}
