package com.pigtrax.usermanagement.service;

import java.sql.SQLException;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import com.pigtrax.usermanagement.beans.Company;
import com.pigtrax.usermanagement.beans.Employee;
import com.pigtrax.usermanagement.dao.interfaces.CompanyDao;
import com.pigtrax.usermanagement.dao.interfaces.EmployeeDao;
import com.pigtrax.usermanagement.dto.EmployeeDto;
import com.pigtrax.usermanagement.service.interfaces.EmployeeService;
@Repository
public class EmployeeServiceImpl implements EmployeeService {

	@Autowired
	EmployeeDao employeeDao;
	
	@Autowired
	CompanyDao companyDao;
	
	@Override
	public String resetPassword(String oldPassword, String newPassword) {
		
		return employeeDao.resetPassword(oldPassword,newPassword);
	}
	@Override
	public List<EmployeeDto> getEmployeeList() {
		
		return employeeDao.getEmployeeList();
	}
	@Override
	public int insertEmployeeRecord(Employee employee) throws SQLException {
		
		return employeeDao.insertEmployeeRecord(employee);
	}
	
	@Override
	public Employee getEmployeeById(int empId) {
		
		Employee emp = employeeDao.getEmployeeById(empId);
		if(emp != null)
		{
		 try {
				Company companyDetails = companyDao.findByCompanyByAutoGeneratedId(emp.getCompanyId());
				emp.setCompanyIdValue(companyDetails.getCompanyId());
				emp.setCompanyName(companyDetails.getName());
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
		return emp;
	}
	@Override
	public int editEmployeeRecord(Employee employee) {
		
		return employeeDao.editEmployeeRecord(employee);
	}
	@Override
	public int activateEmployeeStatus(int employeeId) {
		
		return employeeDao.activateEmployeeStatus(employeeId);
	}
	@Override
	public int deActivateEmployeeStatus(int employeeId) {
		
		return employeeDao.deActivateEmployeeStatus(employeeId);
	}
	@Override
	public String forgetPassword(String employeeId) {
		return employeeDao.forgetPassword(employeeId);
	}
	@Override
	public String changePassword(String newPassword, String reEnterPassword,
			String parameter) {
		// TODO Auto-generated method stub
		return employeeDao.changePassword(newPassword, reEnterPassword, parameter);
	}
	
}
