package com.pigtrax.master.service;

import java.sql.SQLException;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;

import com.pigtrax.master.dao.interfaces.SiloDao;
import com.pigtrax.master.dto.Silo;
import com.pigtrax.master.service.interfaces.SiloService;

public class SiloServiceImpl implements SiloService{

	@Autowired
	private SiloDao siloDao;

	@Override
	public List<Silo> getSiloList(int generatedBarnId) {
		return siloDao.getSiloList( generatedBarnId );
	}

	@Override
	public int updateSiloStatus(String siloID, Boolean siloStatus)
			throws SQLException {
		return siloDao.updateSiloStatus(siloID, siloStatus);
	}
	
	@Override
	public int insertSiloRecord(Silo silo) throws SQLException
	{
		return siloDao.insertSiloRecord(silo);
	}
	
	@Override
	public int updateSiloRecord(Silo silo) throws SQLException
	{
		return siloDao.updateSiloRecord(silo);
	}
	
	public Silo findBySiloByAutoGeneratedId(final int generatedSiloId) throws SQLException
	{
		return siloDao.findBySiloByAutoGeneratedId(generatedSiloId);
	}

}
