package com.pigtrax.master.service;

import java.sql.SQLException;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import com.pigtrax.master.dao.interfaces.TransportTrailerDao;
import com.pigtrax.master.dto.TransportTrailer;
import com.pigtrax.master.service.interfaces.TransportTrailerService;

@Repository
public class TransportTrailerServiceImpl implements TransportTrailerService{
	
	@Autowired
	private TransportTrailerDao transportTrailerDao;

	@Override
	public List<TransportTrailer> getTransportTrailerList(int generatedCompanyId) {
		return transportTrailerDao.getTransportTrailerList( generatedCompanyId );
	}

	@Override
	public int insertTransportTrailer(TransportTrailer transportTrailer)
			throws SQLException {
		return transportTrailerDao.insertTransportTrailer(transportTrailer);
	}

	@Override
	public int updateTransportTrailer(TransportTrailer transportTrailer)
			throws SQLException {
		return transportTrailerDao.updateTransportTrailer(transportTrailer);
	}

	@Override
	public TransportTrailer findByTransportTrailerByAutoGeneratedId(
			int generatedTransportTrailerId) throws SQLException {
		return transportTrailerDao.findByTransportTrailerByAutoGeneratedId(generatedTransportTrailerId);
	}

}
