package com.pigtrax.master.service;

import java.sql.SQLException;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import com.pigtrax.master.dao.interfaces.TransportTruckDao;
import com.pigtrax.master.dto.TransportTruck;
import com.pigtrax.master.service.interfaces.TransportTruckService;

@Repository
public class TransportTruckServiceImpl implements TransportTruckService{

	@Autowired
	private TransportTruckDao transportTruckDao;

	@Override
	public List<TransportTruck> getTransportTruckList(int generatedCompanyId) {
		return transportTruckDao.getTransportTruckList( generatedCompanyId );
	}

	@Override
	public int insertTransportTruck(TransportTruck transportTruck)
			throws SQLException {
		return transportTruckDao.insertTransportTruck(transportTruck);
	}

	@Override
	public int updateTransportTruck(TransportTruck transportTruck)
			throws SQLException {
		return transportTruckDao.updateTransportTruck(transportTruck);
	}

	@Override
	public TransportTruck findByTransportTruckByAutoGeneratedId(
			int generatedTransportTruckId) throws SQLException {
		return transportTruckDao.findByTransportTruckByAutoGeneratedId(generatedTransportTruckId);
	}

}
